fix：Handling test issues and others
masastack/MASA.MC pull request #241
Opened 2022-08-18 02:13 UTC by wzh425

# Description
fix：Handling test issues
chore：Update scheduler
refactor：ASPNETCORE_URLS http=>https
refactor：No sending policy is set. Do not leave the scheduler

2022-08-18 03:17 UTC, doddgu requested changes

2022-08-18 03:17 UTC, doddgu commented on src/Services/Masa.Mc.Service/Masa.Mc.Service.Admin.csproj
> +		<PackageReference Include="Masa.Contrib.ReadWriteSpliting.Cqrs" Version="0.6.0-preview.3" />
?

2022-08-18 09:45 UTC, wzh425 commented on src/Services/Masa.Mc.Service/Masa.Mc.Service.Admin.csproj
> +		<PackageReference Include="Masa.Contrib.ReadWriteSpliting.Cqrs" Version="0.6.0-preview.3" />
最高版本就是0.6.0-preview.3

2022-08-18 10:08 UTC, doddgu commented on src/Services/Masa.Mc.Service/Masa.Mc.Service.Admin.csproj
> +		<PackageReference Include="Masa.Contrib.ReadWriteSpliting.Cqrs" Version="0.6.0-preview.3" />
包名换了 Masa.Contrib.ReadWriteSplitting.Cqr

2022-08-19 01:08 UTC, doddgu approved these changes
LGTM

2022-08-19 01:08 UTC, merged