refactor : ddd cqrs
masastack/MASA.MC pull request #266
Opened 2022-12-02 09:27 UTC by wzh425

1、refactor: ChannelType use Enumeration,and provide different implementations ，kill the switch(src/Services/Masa.Mc.Service/Domain/Channels/Aggregates/ChannelType.cs)
2、refactor: 发送前可以编辑的收件人数据冗余，解析后的收件人数据不冗余，只保存发消息需要的渠道用户数据
3、refactor: api调用发送消息分开成外部用户和内部用户
4、refactor:cqrs，建立查询模型和上下文，查询事件使用查询上下文
4、refactor: ddd  聚合根中抽出一些值对象，应用层业务迁移到领域服务、聚合根、值对象、基础设施内（25%，做了业务代码迁移聚合根内部还未好好提炼）

2022-12-02 10:46 UTC, doddgu requested changes

2022-12-02 10:46 UTC, doddgu commented on src/Infrastructure/Masa.Mc.Infrastructure.Common/Utils/Check.cs
> +public static class Check
MASA Framework has this class. You can ask zhenlei.

2022-12-02 10:46 UTC, doddgu commented on src/Infrastructure/Masa.Mc.Infrastructure.EntityFrameworkCore/Extensions/QueryableExtensions.cs
> +public static class QueryableExtensions
I think it need to move to MASA.Framework.

2022-12-02 10:46 UTC, doddgu commented on src/Services/Masa.Mc.Service/Domain/WebsiteMessages/EventHandler/WebsiteMessageCreatedEventHandler.cs
> +            //var receiver = new Receiver(currentUser.Id, currentUser.DisplayName, currentUser.Avatar, currentUser.PhoneNumber, currentUser.Email);
?

2022-12-02 10:46 UTC, doddgu commented on src/Services/Masa.Mc.Service/Infrastructure/EntityFrameworkCore/McQueryContext.cs
> +        //builder.Entity<WebsiteMessageCursor>(b =>
?

2022-12-02 11:15 UTC, wzh425 commented on src/Services/Masa.Mc.Service/Domain/WebsiteMessages/EventHandler/WebsiteMessageCreatedEventHandler.cs
> +            //var receiver = new Receiver(currentUser.Id, currentUser.DisplayName, currentUser.Avatar, currentUser.PhoneNumber, currentUser.Email);
This is not the latest code. Message records do not require redundant additional user information, but only userid and channel user ID

2022-12-02 11:19 UTC, wzh425 commented on src/Services/Masa.Mc.Service/Infrastructure/EntityFrameworkCore/McQueryContext.cs
> +        //builder.Entity<WebsiteMessageCursor>(b =>
这是为查询上下文的ef配置，用于查询事件，如果读写不分离  建立领域模型时还要兼顾查询场景下 会让建立聚合根时非常难受

2022-12-02 11:21 UTC, wzh425 commented on src/Services/Masa.Mc.Service/Infrastructure/EntityFrameworkCore/McQueryContext.cs
> +        //builder.Entity<WebsiteMessageCursor>(b =>
查询事件里 没有这个站内行游标  他在命令事件下才需要查询

2022-12-02 11:26 UTC, wzh425 commented on src/Services/Masa.Mc.Service/Infrastructure/EntityFrameworkCore/McQueryContext.cs
> +        //builder.Entity<WebsiteMessageCursor>(b =>
Most of the time, two models should be in one aggregation root, but for the convenience of query, they are separated into two aggregation roots, which makes me very uncomfortable

2022-12-05 01:12 UTC, wzh425 commented on src/Infrastructure/Masa.Mc.Infrastructure.Common/Utils/Check.cs
> +public static class Check
MasaArgumentException. ThrowIfNull is not marked with [NotNull], which cannot eliminate the nullable prompt

2022-12-05 07:17 UTC, doddgu approved these changes
LGTM

2022-12-05 07:17 UTC, merged