feat：Add synchronized Alibaba cloud SMS template
masastack/MASA.MC pull request #6
Opened 2022-04-22 02:23 UTC by wzh425

2022-04-24 08:39 UTC, MayueCif commented on src/Contracts/Masa.Mc.Contracts.Admin/Options/Channels/WebsiteMessageChannelOptions.cs
> -    public string Environment { get; set; } = string.Empty;
empty class?

2022-04-24 08:40 UTC, MayueCif commented on src/Contracts/Masa.Mc.Contracts.Admin/Dtos/MessageTemplates/MessageTemplateCreateUpdateDto.cs
> +    [MaxLength(10, ErrorMessage = "Name must be less than 10 characters")]
why not use fluent validator

2022-04-24 08:42 UTC, MayueCif commented on src/Infrastructure/Masa.Mc.Infrastructure.Sms/Services/ISmsTemplateService.cs
> +    Task<SmsResponseBase> GetSmsTemplateListAsync(int pageIndex = 1, int pageSize = 50);
rename pageindex to page

2022-04-24 08:53 UTC, MayueCif commented on src/Web/Masa.Mc.Web.Admin/Pages/ReceiverGroups/Modules/ReceiverGroupCard.razor
> +        <span class="text-body2 neutral-lighten-4--text">吴自浩 编辑于 @Model.ModificationTime.Humanize() </span>
add CultureInfo param

2022-04-24 09:02 UTC, MayueCif commented on src/Web/Masa.Mc.Web.Admin/Pages/MessageTemplates/Modules/EmailTemplateCreateModal.razor.cs
> +        if (_channelItems.Count == 1)
any()

2022-04-24 09:03 UTC, MayueCif commented on src/Web/Masa.Mc.Web.Admin/Pages/MessageTemplates/Modules/SmsTemplateCreateModal.razor.cs
> +
blank line

2022-04-24 09:11 UTC, wzh425 commented on src/Web/Masa.Mc.Web.Admin/Pages/MessageTemplates/Modules/EmailTemplateCreateModal.razor.cs
> +        if (_channelItems.Count == 1)
The requirement is that only one piece of data will be selected by default

2022-04-25 01:33 UTC, MayueCif commented on src/Infrastructure/Masa.Mc.Infrastructure.Sms.Aliyun/Services/SmsTemplateService.cs
> +        QuerySmsTemplateListRequest querySmsTemplateListRequest = new QuerySmsTemplateListRequest() { PageIndex = page, PageSize = pageSize };
pageindex = page ->page=page

2022-04-25 01:34 UTC, MayueCif approved these changes

2022-04-25 01:34 UTC, MayueCif commented
@doddgu LGTM

2022-04-25 02:55 UTC, doddgu requested changes

2022-04-25 02:55 UTC, doddgu commented on src/Infrastructure/Masa.Mc.Infrastructure.Common/Extensions/FluentValidationExtensions.cs
> +public static class FluentValidationExtensions
You can move the extensions to MASA.Utils.

2022-04-25 02:55 UTC, doddgu commented on src/Web/Masa.Mc.Web.Admin/Pages/MessageTemplates/EmailTemplateManagement.razor
> +            <span class="ml-2">@T("Permission:Create")</span>
Usually use `.` as a separator.

2022-04-25 02:55 UTC, doddgu commented on src/Web/Masa.Mc.Web.Admin/wwwroot/i18n/en-US.json
> +  "DisplayName:SmsTemplateType.VerificationCode": "Verification code",
The root don't need another seperator.

2022-04-25 04:41 UTC, doddgu approved these changes

2022-04-25 04:41 UTC, merged