refactor(ui):restore task details and message record details UI,css3 animation
masastack/MASA.MC pull request #66
Opened 2022-06-21 06:30 UTC by wzh425

2022-06-21 07:39 UTC, MayueCif commented on src/Contracts/Masa.Mc.Contracts.Admin/Enums/MessageTasks/MessageTaskHistoryStatuses.cs
> +    Success = 101,
1 101?

2022-06-21 08:03 UTC, MayueCif commented on src/Web/Masa.Mc.Web.Admin/Pages/MessageTasks/Modules/OrdinaryMessageInfo.razor
> +    <dl class="mt-8">
mt-8 change to parent pt-8

2022-06-21 08:04 UTC, MayueCif reviewed
@wzh425

2022-06-21 08:45 UTC, MayueCif approved these changes
@doddgu LGTM

2022-06-23 01:35 UTC, doddgu requested changes

2022-06-23 01:35 UTC, doddgu commented on src/Web/Masa.Mc.Web.Admin.Server/Pages/_Layout.cshtml
> +    <link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" rel="stylesheet" />
Use MASA CDN, and why you need add animate?

2022-06-23 01:36 UTC, wzh425 commented on src/Web/Masa.Mc.Web.Admin.Server/Pages/_Layout.cshtml
> +    <link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" rel="stylesheet" />
animate. CSS brings some auxiliary classes of animate

2022-06-23 02:09 UTC, doddgu approved these changes
LGTM

2022-06-23 02:09 UTC, merged