feat：add messageTask modular
masastack/MASA.MC pull request #7
Opened 2022-04-28 08:01 UTC by wzh425

2022-04-29 02:28 UTC, MayueCif commented on src/Contracts/Masa.Mc.Contracts.Admin/Dtos/MessageTasks/ReceiverItemDto.cs
> +    public string DataId { get; set; } = string.Empty;
SubjectId

2022-04-29 02:30 UTC, MayueCif commented on src/Contracts/Masa.Mc.Contracts.Admin/Dtos/MessageTasks/Validator/MessageTaskCreateUpdateDtoValidator.cs
> +        RuleFor(input => input.Receivers).Must(x => x.Items != null && x.Items.Count > 0).When(x => x.ReceiverType == ReceiverType.Assign);
x.Items?.Any()

2022-04-29 02:31 UTC, MayueCif commented on src/Contracts/Masa.Mc.Contracts.Admin/Dtos/MessageTasks/Validator/SendMessageTaskInputValidator.cs
> +        RuleFor(input => input.Receivers).Must(x => x.Items != null && x.Items.Count > 0).When(x => x.ReceiverType == ReceiverType.Assign);
Any

2022-04-29 02:33 UTC, MayueCif commented on src/Contracts/Masa.Mc.Contracts.Admin/Dtos/ReceiverGroups/ReceiverImportDto.cs
> +    ///  昵称
Modify comment

2022-04-29 02:34 UTC, MayueCif commented on src/Infrastructure/Masa.Mc.Infrastructure.ObjectExtending/ObjectExtending/ExtensionPropertyHelper.cs
> +﻿using System.Text.Json;
global using

2022-04-29 03:03 UTC, MayueCif commented on src/Services/Masa.Mc.Service/Infrastructure/EntityFrameworkCore/McDbContext.cs
> +            b.Property(x => x.Code).IsRequired().HasMaxLength(64).HasColumnName(nameof(Channel.Code));
default value is property name

2022-04-29 03:49 UTC, wzh425 commented on src/Services/Masa.Mc.Service/Infrastructure/EntityFrameworkCore/McDbContext.cs
> +            b.Property(x => x.Code).IsRequired().HasMaxLength(64).HasColumnName(nameof(Channel.Code));
Shared entity needs HasColumnName

2022-04-29 05:38 UTC, MayueCif approved these changes

2022-04-29 05:39 UTC, MayueCif commented
@doddgu LGTM

2022-05-05 10:43 UTC, MayueCif commented on src/Contracts/Masa.Mc.Contracts.Admin/Dtos/MessageTasks/MessageTaskHistoryDto.cs
> +    public ReceiverType ReceiverType { get; set; }
ReceiverTypes

2022-05-05 10:45 UTC, MayueCif commented on src/Contracts/Masa.Mc.Contracts.Admin/Dtos/MessageTasks/ReceiverItemDto.cs
> +    public MessageTaskReceiverType Type { get; set; }
MessageTaskReceiverTypes

2022-05-05 10:48 UTC, MayueCif commented on src/Contracts/Masa.Mc.Contracts.Admin/Dtos/MessageTasks/SendingRuleDto.cs
> +public class SendingRuleDto
ing?

2022-05-05 10:54 UTC, MayueCif commented on src/Contracts/Masa.Mc.Contracts.Admin/Dtos/MessageTasks/DisableMessageTaskInput.cs
> +public class DisableMessageTaskInput
Input -> InputDto

2022-05-05 11:05 UTC, MayueCif commented on src/Contracts/Masa.Mc.Contracts.Admin/Dtos/MessageTemplates/SmsTemplateSynchroInput.cs
>  public class SmsTemplateSynchroInput
Synchro -> Sync

2022-05-05 11:07 UTC, MayueCif commented on src/Contracts/Masa.Mc.Contracts.Admin/Enums/Channels/ChannelType.cs
>  public enum ChannelType
ChannelTypes

2022-05-05 11:07 UTC, MayueCif commented on src/Contracts/Masa.Mc.Contracts.Admin/Enums/MessageTasks/MessageEntityType.cs
> +public enum MessageEntityType
MessageEntityTypes

2022-05-05 11:07 UTC, MayueCif commented on src/Contracts/Masa.Mc.Contracts.Admin/Enums/MessageTasks/MessageTaskHistoryStatus.cs
> +public enum MessageTaskHistoryStatus
MessageTaskHistoryStatuses

2022-05-05 11:07 UTC, MayueCif commented on src/Contracts/Masa.Mc.Contracts.Admin/Enums/MessageTasks/MessageTaskReceiverType.cs
> +public enum MessageTaskReceiverType
MessageTaskReceiverTypes

2022-05-06 03:55 UTC, MayueCif commented on src/Contracts/Masa.Mc.Contracts.Admin/Dtos/MessageTemplates/MessageTemplateCreateUpdateDto.cs
>      public long DayLimit { get; set; }
per day

2022-05-06 04:20 UTC, MayueCif commented on src/Infrastructure/Masa.Mc.Infrastructure.Common/Extensions/CollectionExtensions.cs
> +        foreach (var item in items)
like this source.AddRange(item.Where(a=>source.Contains(a)));

2022-05-06 04:22 UTC, MayueCif commented on src/Infrastructure/Masa.Mc.Infrastructure.Common/Extensions/CollectionExtensions.cs
>          var items = source.Where(predicate).ToList();
source.ToList().RemoveAll(predicate);

2022-05-06 04:24 UTC, MayueCif commented on src/Infrastructure/Masa.Mc.Infrastructure.Common/Extensions/DictionaryExtensions.cs
> +    public static TValue GetOrDefault<TKey, TValue>(this IDictionary<TKey, TValue> dictionary, TKey key)
repeat 40 line

2022-05-06 04:33 UTC, MayueCif commented on src/Infrastructure/Masa.Mc.Infrastructure.Common/Extensions/EnumerableExtensions.cs
> +    public static string JoinAsString(this IEnumerable<string> source, string separator)
this extension method whether or not necessary

2022-05-06 04:40 UTC, MayueCif commented on src/Infrastructure/Masa.Mc.Infrastructure.Common/Extensions/StringExtensions.cs
> +    public static string ToKebabCase(this string str, bool useCurrentCulture = false)
public static string ToKebabCase(this string str)
        {
            if (string.IsNullOrEmpty(str))
            {
                return str;
            }
            return Regex.Replace(str, @"(\B[A-Z])", "-$1").ToLower();
        }

2022-05-06 04:41 UTC, MayueCif commented on src/Infrastructure/Masa.Mc.Infrastructure.Common/Helper/TypeHelper.cs
> +        {
format

2022-05-06 04:42 UTC, MayueCif commented on src/Infrastructure/Masa.Mc.Infrastructure.Email/EmailSenderBase.cs
> +            mail.HeadersEncoding = Encoding.UTF8;
mail.HeadersEncoding = mail.HeadersEncoding??Encoding.UTF8;

2022-05-06 05:01 UTC, MayueCif commented on src/Infrastructure/Masa.Mc.Infrastructure.Email/Infrastructure/OptionsResolve/Contributors/ConfigurationOptionsResolveContributor.cs
> +    public const string ContributorName = "Configuration";
const name rule all upper

2022-05-06 05:04 UTC, MayueCif commented on src/Infrastructure/Masa.Mc.Infrastructure.Email/Infrastructure/OptionsResolve/IEmailOptionsResolver.cs
> +    Task<IEmailOptions> ResolveAsync();
Resolve？

2022-05-06 05:43 UTC, MayueCif commented on src/Services/Masa.Mc.Service/Domain/MessageTemplates/EventHandler/MessageTemplateAuditStatusChangedEventHandler.cs
> +        entity.SetAuditStatus(MessageTemplateAuditStatues.Adopt, @event.Remarks);
Statues?Statuses

2022-05-06 06:24 UTC, MayueCif commented on src/Web/Masa.Mc.Web.Admin/Pages/MessageTasks/Modules/MessageSendingRules.razor.cs
> +    public DateOnly? sendingDate;
public filed?

2022-05-06 06:33 UTC, MayueCif commented on src/Web/Masa.Mc.Web.Admin/Shared/MessageType.cs
> -﻿using System;
delete MessageType.cs

2022-05-06 06:43 UTC, MayueCif reviewed
modify by conversation

2022-05-06 06:57 UTC, doddgu requested changes

2022-05-06 07:16 UTC, wzh425 commented on src/Infrastructure/Masa.Mc.Infrastructure.Common/Extensions/CollectionExtensions.cs
> +        foreach (var item in items)
ICollection does not have AddRange method

2022-05-06 07:17 UTC, wzh425 commented on src/Infrastructure/Masa.Mc.Infrastructure.Common/Extensions/CollectionExtensions.cs
>          var items = source.Where(predicate).ToList();
ToList Will cause EF save

2022-05-10 01:59 UTC, wzh425 commented on src/Contracts/Masa.Mc.Contracts.Admin/Dtos/MessageTasks/EnabledMessageTaskInput.cs
> +public class EnabledMessageTaskInput
post body parameter

2022-05-10 04:02 UTC, merged