Feature/message task
masastack/MASA.MC pull request #8
Opened 2022-05-10 14:38 UTC by wzh425

2022-05-12 05:35 UTC, MayueCif commented on src/Contracts/Masa.Mc.Contracts.Admin/Dtos/MessageTasks/Validator/MessageTaskUpsertDtoValidator.cs
> +        RuleFor(inputDto => inputDto.EntityId).Required().When(x => x.EntityType == MessageEntityTypes.Template).When(x => !x.IsDraft);
x?

2022-05-12 05:35 UTC, MayueCif commented on src/Services/Masa.Mc.Service/Application/MessageRecords/MessageRecordQueryHandler.cs
>          Expression<Func<MessageRecord, bool>> condition = x => true;
renmae x

2022-05-12 05:39 UTC, MayueCif commented on src/Services/Masa.Mc.Service/Application/ReceiverGroups/ReceiverGroupQueryHandler.cs
> +        condition = condition.And(!string.IsNullOrEmpty(inputDto.Filter), x => x.DisplayName.Contains(inputDto.Filter));
x?

2022-05-12 05:39 UTC, MayueCif commented on src/Services/Masa.Mc.Service/Infrastructure/EntityFrameworkCore/McDbContextModelBuilderExtensions.cs
>              b.Property(x => x.DisplayName).IsRequired().HasMaxLength(128);
x->c

2022-05-12 05:43 UTC, MayueCif commented on src/Web/Masa.Mc.Web.Admin/Components/Modules/Subjects/UserSelect.razor.cs
> +    public Guid? Value { get; set; }
why guid?

2022-05-12 05:43 UTC, MayueCif commented on src/Web/Masa.Mc.Web.Admin/Components/Modules/Subjects/UserSelect.razor.cs
> +    public string? Label { get; set; }
string?

2022-05-12 05:44 UTC, MayueCif commented on src/Web/Masa.Mc.Web.Admin/Components/Selects/BooleanSelect.razor.cs
> +    public bool? Value { get; set; }
use default value replace nullable

2022-05-12 05:48 UTC, MayueCif commented on src/Web/Masa.Mc.Web.Admin/Data/Auth/Subjects/Dto/CreateExternalUserDtoValidator.cs
> -        RuleFor(inputDto => inputDto.PhoneNumber).Required().Phone().When(x=>string.IsNullOrEmpty(x.Email));
x

2022-05-12 05:51 UTC, MayueCif commented on src/Web/Masa.Mc.Web.Admin/Pages/MessageTasks/Modules/MessageReceivers.razor.cs
> +        var receiverGroups = (await ReceiverGroupService.GetListAsync(_queryParam)).Result.Select(x => new SubjectDto
x

2022-05-12 05:56 UTC, MayueCif commented on src/Web/Masa.Mc.Web.Admin/Pages/MessageTasks/Modules/MessageTaskSendModal.razor.cs
> +        try
why not handler exception by MErrorHandler

2022-05-12 05:56 UTC, MayueCif commented on src/Web/Masa.Mc.Web.Admin/Pages/MessageTasks/Modules/OrdinaryMessageCreateModal.razor.cs
> +        try
why not handler exception by MErrorHandler

2022-05-12 06:05 UTC, MayueCif reviewed
@wzh425 PTAL

2022-05-12 09:33 UTC, wzh425 commented on src/Web/Masa.Mc.Web.Admin/Components/Selects/BooleanSelect.razor.cs
> +    public bool? Value { get; set; }
Business needs can be blank

2022-05-12 10:20 UTC, wzh425 commented on src/Web/Masa.Mc.Web.Admin/Components/Modules/Subjects/UserSelect.razor.cs
> +    public Guid? Value { get; set; }
The swagger parameter becomes mandatory

2022-05-13 01:54 UTC, MayueCif approved these changes

2022-05-13 01:54 UTC, MayueCif commented
@doddgu LGTM

2022-05-13 05:55 UTC, doddgu requested changes

2022-05-13 05:55 UTC, doddgu commented on src/Infrastructure/Masa.Mc.Infrastructure.Common/Helper/UtilConvert.cs
> +    public static string Number(int Length)
Length -> length

2022-05-13 05:55 UTC, doddgu commented on src/Infrastructure/Masa.Mc.Infrastructure.Common/Helper/UtilConvert.cs
> +    public static string Number(int Length, bool Sleep)
Length -> length, Sleep -> sleep.

2022-05-13 05:55 UTC, doddgu commented on src/Infrastructure/Masa.Mc.Infrastructure.Common/Helper/UtilConvert.cs
> +            System.Threading.Thread.Sleep(3);
Thread.Sleep -> Task.Delay

2022-05-13 05:55 UTC, doddgu commented on src/Infrastructure/Masa.Mc.Infrastructure.Common/Helper/UtilConvert.cs
> +        System.Random random = new Random();
Random.Shared can remove the sleep?

2022-05-13 05:55 UTC, doddgu commented on src/Infrastructure/Masa.Mc.Infrastructure.Common/Helper/UtilConvert.cs
> +    public static string Number(int Length, bool Sleep)
refactor the Number method.

2022-05-13 05:55 UTC, doddgu commented on src/Infrastructure/Masa.Mc.Infrastructure.Common/Helper/UtilConvert.cs
> +        long num2 = DateTime.Now.Ticks + rep;
Why does ticks need add 0?

2022-05-13 05:55 UTC, doddgu commented on src/Infrastructure/Masa.Mc.Infrastructure.Common/Helper/UtilConvert.cs
> +    public static string GetCheckCode(int codeCount)
What's the mean of check code?

2022-05-13 05:55 UTC, doddgu commented on src/Services/Masa.Mc.Service/Domain/MessageRecords/EventHandler/CreateMessageEventHandler.cs
> +        var _messageTaskHistoryRepository = unitOfWork.ServiceProvider.GetRequiredService<IMessageTaskHistoryRepository>();
remove the prefix _

2022-05-13 05:55 UTC, doddgu commented on src/Services/Masa.Mc.Service/Domain/MessageRecords/EventHandler/CreateMessageEventHandler.cs
> +        await using var unitOfWork = unitOfWorkManager.CreateDbContext();
Why you need create dbcontext here? @MayueCif

2022-05-13 05:55 UTC, doddgu commented on src/Services/Masa.Mc.Service/Domain/MessageRecords/EventHandler/SendEmailMessageEventHandler.cs
> +        var unitOfWorkManager = _serviceProvider.GetRequiredService<IUnitOfWorkManager>();
@MayueCif

2022-05-13 05:55 UTC, doddgu commented on src/Services/Masa.Mc.Service/Domain/MessageRecords/EventHandler/SendSmsMessageEventHandler.cs
> +        var unitOfWorkManager = _serviceProvider.GetRequiredService<IUnitOfWorkManager>();
@MayueCif

2022-05-13 05:55 UTC, doddgu commented on src/Services/Masa.Mc.Service/Domain/MessageTasks/Aggregates/AppMessageTask.cs
> +    public MessageEntityTypes EntityType { get; protected set; }
EntityType?

2022-05-13 05:55 UTC, doddgu commented on src/Services/Masa.Mc.Service/Domain/MessageTasks/Aggregates/AppMessageTask.cs
> +    public Guid EntityId { get; protected set; }
EntityId?

2022-05-13 05:55 UTC, doddgu commented on src/Services/Masa.Mc.Service/Domain/MessageTasks/EventHandler/AddMessageTaskHistoryEventHandler.cs
> +        var taskHistoryNo = $"SJ{UtilConvert.GetGuidToNumber()}";
Why has it SJ prefix?

2022-05-13 05:55 UTC, doddgu commented on src/Services/Masa.Mc.Service/Domain/MessageTemplates/EventHandler/SmsTemplateSynchroEventHandler.cs
> +        var unitOfWorkManager = _serviceProvider.GetRequiredService<IUnitOfWorkManager>();
@MayueCif

2022-05-13 05:55 UTC, doddgu commented on src/Web/Masa.Mc.Web.Admin/Masa.Mc.Web.Admin.csproj
> +    <PackageReference Include="Masa.Blazor" Version="0.4.0-preview.22" />
preview.22 is deleted

2022-05-13 06:13 UTC, wzh425 commented on src/Services/Masa.Mc.Service/Domain/MessageRecords/EventHandler/SendEmailMessageEventHandler.cs
> +        var unitOfWorkManager = _serviceProvider.GetRequiredService<IUnitOfWorkManager>();
It has been modified. Createasyncscope will not be processed in the handler before the event is sent

2022-05-13 06:34 UTC, wzh425 commented on src/Services/Masa.Mc.Service/Domain/MessageTasks/EventHandler/AddMessageTaskHistoryEventHandler.cs
> +        var taskHistoryNo = $"SJ{UtilConvert.GetGuidToNumber()}";
Prototype design

2022-05-13 06:38 UTC, wzh425 commented on src/Web/Masa.Mc.Web.Admin/Masa.Mc.Web.Admin.csproj
> +    <PackageReference Include="Masa.Blazor" Version="0.4.0-preview.22" />
0.4.0-preview. 1. The global exception component has a bug

2022-05-13 06:56 UTC, wzh425 commented on src/Infrastructure/Masa.Mc.Infrastructure.Common/Helper/UtilConvert.cs
> +    public static string Number(int Length)
Unused method, removed

2022-05-13 06:56 UTC, wzh425 commented on src/Infrastructure/Masa.Mc.Infrastructure.Common/Helper/UtilConvert.cs
> +    public static string Number(int Length, bool Sleep)
Unused method, removed

2022-05-13 06:56 UTC, wzh425 commented on src/Infrastructure/Masa.Mc.Infrastructure.Common/Helper/UtilConvert.cs
> +            System.Threading.Thread.Sleep(3);
Unused method, removed

2022-05-13 06:56 UTC, wzh425 commented on src/Infrastructure/Masa.Mc.Infrastructure.Common/Helper/UtilConvert.cs
> +        System.Random random = new Random();
Unused method, removed

2022-05-13 06:56 UTC, wzh425 commented on src/Infrastructure/Masa.Mc.Infrastructure.Common/Helper/UtilConvert.cs
> +    public static string Number(int Length, bool Sleep)
Unused method, removed

2022-05-13 06:56 UTC, wzh425 commented on src/Infrastructure/Masa.Mc.Infrastructure.Common/Helper/UtilConvert.cs
> +        long num2 = DateTime.Now.Ticks + rep;
Unused method, removed

2022-05-13 06:56 UTC, wzh425 commented on src/Infrastructure/Masa.Mc.Infrastructure.Common/Helper/UtilConvert.cs
> +    public static string GetCheckCode(int codeCount)
Unused method, removed

2022-05-13 07:01 UTC, wzh425 commented on src/Services/Masa.Mc.Service/Domain/MessageRecords/EventHandler/CreateMessageEventHandler.cs
> +        await using var unitOfWork = unitOfWorkManager.CreateDbContext();
It has been modified. Createasyncscope is now placed before the event. There is no need to create dbcontext here

2022-05-13 07:01 UTC, wzh425 commented on src/Services/Masa.Mc.Service/Domain/MessageRecords/EventHandler/SendSmsMessageEventHandler.cs
> +        var unitOfWorkManager = _serviceProvider.GetRequiredService<IUnitOfWorkManager>();
It has been modified. Createasyncscope is now placed before the event. There is no need to create dbcontext here

2022-05-13 07:01 UTC, wzh425 commented on src/Services/Masa.Mc.Service/Domain/MessageTemplates/EventHandler/SmsTemplateSynchroEventHandler.cs
> +        var unitOfWorkManager = _serviceProvider.GetRequiredService<IUnitOfWorkManager>();
It has been modified. Createasyncscope is now placed before the event. There is no need to create dbcontext here

2022-05-13 07:05 UTC, wzh425 commented on src/Services/Masa.Mc.Service/Domain/MessageTasks/Aggregates/AppMessageTask.cs
> +    public Guid EntityId { get; protected set; }
Entity ID associated with message content

2022-05-13 07:10 UTC, wzh425 commented on src/Web/Masa.Mc.Web.Admin/Masa.Mc.Web.Admin.csproj
> +    <PackageReference Include="Masa.Blazor" Version="0.4.0-preview.22" />
Updated 0.4.0-preview.4

2022-05-13 07:12 UTC, wzh425 commented on src/Services/Masa.Mc.Service/Domain/MessageRecords/EventHandler/CreateMessageEventHandler.cs
> +        var _messageTaskHistoryRepository = unitOfWork.ServiceProvider.GetRequiredService<IMessageTaskHistoryRepository>();
Serviceprovider is no longer required here

2022-05-13 07:52 UTC, wzh425 commented on src/Services/Masa.Mc.Service/Domain/MessageTasks/Aggregates/AppMessageTask.cs
> +    public MessageEntityTypes EntityType { get; protected set; }
Entity type associated with message content

2022-05-13 07:53 UTC, wzh425 commented on src/Services/Masa.Mc.Service/Domain/MessageTasks/EventHandler/AddMessageTaskHistoryEventHandler.cs
> +        var taskHistoryNo = $"SJ{UtilConvert.GetGuidToNumber()}";
At present, the demand is temporary, and the generation rules are to be determined

2022-05-16 01:32 UTC, doddgu requested changes

2022-05-16 01:32 UTC, doddgu commented on src/Services/Masa.Mc.Service/Domain/Channels/Services/ChannelDomainService.cs
> +                var eventBus = scope.ServiceProvider.GetRequiredService<IDomainEventBus>();
Why not use eventBus from constructor?

2022-05-16 01:32 UTC, doddgu commented on src/Web/Masa.Mc.Web.Admin/Pages/Channels/Modules/ChannelSmsExtraProperties.razor.cs
> +
Remove the blank line

2022-05-16 01:33 UTC, doddgu commented on src/Services/Masa.Mc.Service/Domain/MessageTasks/Aggregates/AppMessageTask.cs
> +    public MessageEntityTypes EntityType { get; protected set; }
I mean why not named MessageType?

2022-05-16 01:33 UTC, doddgu commented on src/Services/Masa.Mc.Service/Domain/MessageTasks/Aggregates/AppMessageTask.cs
> +    public Guid EntityId { get; protected set; }
MessageId?

2022-05-16 01:43 UTC, wzh425 commented on src/Services/Masa.Mc.Service/Domain/Channels/Services/ChannelDomainService.cs
> +                var eventBus = scope.ServiceProvider.GetRequiredService<IDomainEventBus>();
In this way, the connection will be released when operating data in EventHandler

2022-05-16 01:44 UTC, wzh425 commented on src/Services/Masa.Mc.Service/Domain/Channels/Services/ChannelDomainService.cs
> +                var eventBus = scope.ServiceProvider.GetRequiredService<IDomainEventBus>();
Now it's better to wait for the completion of task execution instead of using task Run

2022-05-16 03:30 UTC, doddgu approved these changes
LGTM

2022-05-16 03:30 UTC, merged