refactor：Modify useswaggerui environment restrictions
masastack/MASA.MC pull request #9
Opened 2022-05-16 06:46 UTC by wzh425

2022-05-19 05:28 UTC, MayueCif commented on src/Contracts/Masa.Mc.Contracts.Admin/Dtos/MessageTasks/MessageTaskDto.cs
> +    public MessageTaskReceiverSelectTypes ReceiverSelectType { get; set; }
SelectReceiverTypes

2022-05-19 05:30 UTC, MayueCif commented on src/Contracts/Masa.Mc.Contracts.Admin/Enums/MessageTasks/MessageTaskReceiverSelectTypes.cs
> +public enum MessageTaskReceiverSelectTypes
SelectReceiverTypes

2022-05-19 05:37 UTC, MayueCif commented on src/Infrastructure/Masa.Mc.Infrastructure.ExporterAndImporter.Csv/CsvExporter.cs
> +
delete line

2022-05-19 05:38 UTC, MayueCif commented on src/Infrastructure/Masa.Mc.Infrastructure.ExporterAndImporter.Csv/CsvImporter.cs
> +    }
add blank line

2022-05-19 06:24 UTC, MayueCif commented on src/Infrastructure/Masa.Mc.Infrastructure.ExporterAndImporter.Csv/Utility/ExportHelper.cs
> +        this._type = type;
remove this.

2022-05-19 06:33 UTC, MayueCif commented on src/Web/Masa.Mc.Web.Admin/Pages/MessageTasks/Modules/MessageReceiversSelect.razor.cs
> +        await ValueChanged.InvokeAsync(Value);
if(ValueChanged.HasDelegate()){
 await ValueChanged.InvokeAsync(Value);
}
else{
//todo
}

2022-05-19 07:27 UTC, MayueCif reviewed
modify

2022-05-23 07:52 UTC, MayueCif approved these changes

2022-05-23 07:53 UTC, MayueCif commented
@doddgu LGTM

2022-05-24 05:15 UTC, doddgu requested changes

2022-05-24 05:15 UTC, doddgu commented on src/Infrastructure/Masa.Mc.Infrastructure.ExporterAndImporter.Csv/CsvExporter.cs
> +    /// <summary>
add blank line

2022-05-24 05:15 UTC, doddgu commented on src/Infrastructure/Masa.Mc.Infrastructure.ExporterAndImporter.Csv/CsvExporter.cs
> +    /// <summary>
add blank line

2022-05-24 05:15 UTC, doddgu commented on src/Infrastructure/Masa.Mc.Infrastructure.ExporterAndImporter.Csv/CsvExporter.cs
> +    ///
remove the comment

2022-05-24 05:15 UTC, doddgu commented on src/Infrastructure/Masa.Mc.Infrastructure.ExporterAndImporter.Csv/CsvExporter.cs
> +/// Csv导出程序
English comment

2022-05-24 05:15 UTC, doddgu commented on src/Infrastructure/Masa.Mc.Infrastructure.ExporterAndImporter.Csv/CsvImporter.cs
> +///     Csv导入
English comment or remove it.

2022-05-24 05:15 UTC, doddgu commented on src/Infrastructure/Masa.Mc.Infrastructure.ExporterAndImporter.Csv/Masa.Mc.Infrastructure.ExporterAndImporter.Csv.csproj
> +    <PackageReference Include="Magicodes.IE.Csv" Version="2.6.4" />
Why using Magicodes.IE.Csv?

2022-05-24 05:15 UTC, doddgu commented on src/Infrastructure/Masa.Mc.Infrastructure.ExporterAndImporter.Csv/Utility/ExportHelper.cs
> +    /// <summary>
Remove the comment

2022-05-24 05:15 UTC, doddgu commented on src/Infrastructure/Masa.Mc.Infrastructure.ExporterAndImporter.Csv/Utility/ImportHelper.cs
> +        /// <summary>
remove the comment

2022-05-24 05:15 UTC, doddgu commented on src/Services/Masa.Mc.Service/Application/Channels/ChannelCommandHandler.cs
> +            throw new UserFriendlyException("There are channel in use and cannot be deleted");
channel -> channels

2022-05-24 05:15 UTC, doddgu commented on src/Services/Masa.Mc.Service/Domain/Channels/Services/ChannelDomainService.cs
> +            throw new UserFriendlyException("channel code cannot be repeated");
channel -> Channel

2022-05-24 05:15 UTC, doddgu commented on src/Services/Masa.Mc.Service/Domain/MessageTemplates/EventHandler/SmsTemplateSynchroEventHandler.cs
> +
remove the blank line.

2022-05-24 05:33 UTC, doddgu approved these changes

2022-05-24 05:33 UTC, merged